### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by iamzubin** [PixlOne/masterOptions#1]
while building on Fedora, I am running into an error

```canning dependencies of target masterd
[ 10%] Building CXX object src/masterd/CMakeFiles/masterd.dir/masterd.cpp.o
[ 20%] Building CXX object src/masterd/CMakeFiles/masterd.dir/Configuration.cpp.o
/home/imzubin/masterOptions/src/masterd/Configuration.cpp: In function ‘ButtonAction* parse_action(Action, const libconfig::Setting*, bool)’:
/home/imzubin/masterOptions/src/masterd/Configuration.cpp:200:40: error: ‘libevdev_event_code_from_code_name’ was not declared in this scope; did you mean ‘libevdev_event_code_from_name’?
  200 |                 unsigned int keycode = libevdev_event_code_from_code_name(keys_config[i]);
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                        libevdev_event_code_from_name
/home/imzubin/masterOptions/src/masterd/Configuration.cpp:201:28: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
  201 |                 if(keycode == -1)
      |                    ~~~~~~~~^~~~~
make[2]: *** [src/masterd/CMakeFiles/masterd.dir/build.make:76: src/masterd/CMakeFiles/masterd.dir/Configuration.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:91: src/masterd/CMakeFiles/masterd.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by iamzubin** [comment]
sorry for this stupid issue, but after fixing a bunch of lib issues, I somehow build the applications,
doing so required adding symlinks to lib64 libraries and installing the latest version of libraries(in testing for Fedora packages)

after doing so I ran into Runtime error

```
➜  build git:(master) ✗ ./masterd 
terminate called after throwing an instance of 'int'
[1]    20764 abort (core dumped)  ./masterd
```
coredump:~
https://drive.google.com/file/d/1qdPn3S-fGZlDMzcDXCJkMC3oe735qR_3/view?usp=sharing

**Comment by PixlOne** [comment]
So I'm looking into this right now, the first part of the issue seems to be an issue with how I link libraries through CMake. The latter part requires you to run masterd as root.

I'll try to fix this bug soon.

P.S. One issue I'm getting on Fedora on QEMU/KVM is that my mouse times out. Can you replicate this once you run masterd as root?

**Comment by iamzubin** [comment]
i actually ran it with sudo

**Comment by PixlOne** [comment]
So I should have fixed the build error here: 10d0a66831a17ed280c2c842bb6c294dd8edb8f3

This shouldn't require any symlink trickery. As for the other issue, I caught that exception so it should tell you what the error code is. Can you tell me what the error message is when you launch it?

**Comment by iamzubin** [comment]
yeah it does timeout
and doesn't map any buttons.

```
➜  build git:(master) ✗ sudo ./masterd
[DEBUG] DPI: 1000
[DEBUG] Smartshift: on
[DEBUG] Smartshift threshold: 30
[WARN] Device /dev/hidraw4 (index 255) timed out.
[WARN] Device /dev/hidraw4 (index 0) timed out.
```

**Comment by PixlOne** [comment]
Yeah, there's currently an issue where it times out because it scans every hidraw device. I'm going to try to limit the scanning to logitech devices to mitigate this.

**Comment by iamzubin** [comment]
does this work on any other distro?

**Comment by PixlOne** [comment]
Arch w/ solaar udev rules allows it to access my logitech reciever's hidraw without root which allows it to bypass this timeout issue by scanning only the recievers.

**Comment by iamzubin** [comment]
but wouldn't that make it work only with usb receiver?

I can still have hidraw device if I connect using Bluetooth.
also, writing custom udev rules it should fix the timeout issue.right?


I tried using udev rules, added your script to the udev script, didn't work
can you please help me setup?

**Comment by iamzubin** [comment]
hey, i did provide all the permissions to a group and added my user to that,
now I can read from the hidraw device and create a input device but script still times out

```
➜  build git:(master) ✗ ls -l /dev/hidraw*         
crwx------. 1 root root  241, 0 Jul 11 13:20 /dev/hidraw0
crwx------. 1 root root  241, 1 Jul 11 13:20 /dev/hidraw1
crwx------. 1 root root  241, 2 Jul 11 13:20 /dev/hidraw2
crwxrw-rw-+ 1 root input 241, 3 Jul 11 14:04 /dev/hidraw3
crwxrw-rw-. 1 root root  241, 4 Jul 11 14:04 /dev/hidraw4
crwx------. 1 root root  241, 5 Jul 11 13:20 /dev/hidraw5
crwx------. 1 root root  241, 6 Jul 11 13:20 /dev/hidraw6
➜  build git:(master) ✗ ls -l /dev/uinput 
crw-rw-rw-. 1 root root 10, 223 Jul 11 13:20 /dev/uinput
➜  build git:(master) ✗ ./masterd         
[DEBUG] DPI: 1000
[DEBUG] Smartshift: on
[DEBUG] Smartshift threshold: 30
[WARN] Device /dev/hidraw4 (index 255) timed out.
[WARN] Device /dev/hidraw4 (index 0) timed out.
[WARN] Failed to open /dev/hidraw0: open: Permission denied
[WARN] Failed to open /dev/hidraw1: open: Permission denied
[WARN] Failed to open /dev/hidraw2: open: Permission denied
[WARN] Failed to open /dev/hidraw5: open: Permission denied
[WARN] Failed to open /dev/hidraw6: open: Permission denied
```

both hidraw3 and 4 shows some output when i move the mouse,
I've also tried individual permissions,
also hidraw3 is detected by solaar.

It shows this error sometimes
```
[WARN] Error while querying /dev/hidraw3, wireless device 1: Resource error
```

**Comment by iamzubin** [comment]
is this supposed to work with mx master 2s aswell?

**Comment by PixlOne** [comment]
I'm not sure, the code is meant to only detect a device named 'MX Master', although you could probably just change that string and get it to work.

Either way, I've stopped working on this project and I'm transitioning this into a more universal Logitech driver called '[logiops](https://github.com/PixlOne/logiops)'
